name: Compilar App Garmin

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Descargar SDK de Connect IQ
        run: |
          mkdir -p garmin-sdk
          # Descarga directa emulando navegador real
          curl -sSL -A "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
            "https://developer.garmin.com/downloads/connect-iq/sdks/connectiq-sdk-lin-7.1.0-2024-03-11-2b0e36a27.zip" -o sdk.zip

          # Verificar si es un zip valido
          if file sdk.zip | grep -q "Zip archive"; then
            unzip -q sdk.zip -d garmin-sdk
            echo "SDK descargado y extraído con éxito."
          else
            echo "Error: Garmin bloqueó la descarga del ZIP."
            exit 1
          fi

      - name: Generar clave desarrollador temporal
        run: |
          openssl genrsa -out developer_key.pem 4096
          openssl pkcs8 -topk8 -inform PEM -outform DER -in developer_key.pem -out developer_key.der -nocrypt

      - name: Compilar archivo PRG
        run: |
          ./garmin-sdk/bin/monkeyc -c 3 -y developer_key.der -o MiPrimeraApp.prg -m manifest.xml -f MiAppView.mc -d fr55

      - name: Guardar ejecutable PRG
        uses: actions/upload-artifact@v4
        with:
          name: Garmin-App-PRG
          path: MiPrimeraApp.prg
          
