name: Compilar App Garmin

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Descargar SDK de Connect IQ
        run: |
          mkdir -p garmin-sdk
          # Descarga desde espejo alojado en GitHub para evitar bloqueo de Garmin
          curl -sSL "https://github.com/puro22/garmin-sdk-mirror/releases/download/v6.4.2/connectiq-sdk-lin-6.4.2-2023-12-07-353d26a27.zip" -o sdk.zip
          
          if file sdk.zip | grep -q "Zip archive"; then
            unzip -q sdk.zip -d garmin-sdk
            echo "SDK descargado y extraído correctamente."
          else
            echo "Error al obtener el archivo ZIP."
            exit 1
          fi

      - name: Generar clave desarrollador temporal
        run: |
          openssl genrsa -out developer_key.pem 4096
          openssl pkcs8 -topk8 -inform PEM -outform DER -in developer_key.pem -out developer_key.der -nocrypt

      - name: Compilar archivo PRG
        run: |
          ./garmin-sdk/bin/monkeyc -c 3 -y developer_key.der -o MiPrimeraApp.prg -m manifest.xml -f MiAppView.mc -d fr55

      - name: Guardar ejecutable PRG
        uses: actions/upload-artifact@v4
        with:
          name: Garmin-App-PRG
          path: MiPrimeraApp.prg
